Repository cyrusimap/cyrus-imapd, pull requests merged in 2021-01, with the labels that each got.

#3312 Fix two use after free segfaults
  imap/backend.c
  imap/backend.h
  imap/mupdate-client.c
  imap/mupdate.h
Labels: 2.4

#3306 jmap_mail: return AttachmentMatch in SearchSnippet/get
  imap/index.c
  imap/jmap_mail.c
  imap/jmap_mail_query.c
  imap/search_engines.h
  imap/search_squat.c
  imap/search_xapian.c
Labels: include-in-fastmail, include-in-fm-cal2020

#3308 jmap_mail: rewrite email query folder-search optimizer to use DNF
  imap/jmap_mail.c
Labels: bug, include-in-fastmail, include-in-fm-cal2020

#3316 squat: fix broken squat engine integration for indexed search
  imap/search_engines.c
  imap/search_engines.h
  imap/search_expr.c
  imap/search_query.c
  imap/search_squat.c
  imap/search_xapian.c
Labels: 3.0

#3295 configurable special-use mailboxes that may not contain children
  cunit/strarray.testc
  imap/annotate.c
  imap/mboxlist.c
  lib/imapoptions
  lib/strarray.c
Labels: include-in-fastmail
