Repository cyrusimap/cyrus-imapd, pull requests merged in 2021-07, with the labels that each got.

#3510 jmap_mail: improve performance of inMailboxOtherThan queries
  imap/jmap_mail.c
  imap/search_query.c
Labels: include-in-fastmail

#3529 UUID legacy paths
  imap/append.c
  imap/cyr_ls.c
  imap/imapd.c
  imap/mailbox.c
  imap/mboxlist.c
  imap/sync_support.c
  sieve/test_mailbox.c
Labels: include-in-fastmail

#3525 jmap_mail: move the 'filln' logic into the inner loops
  imap/jmap_mail.c
Labels: include-in-fastmail

#3524 jmap_mail: fix 'hasKeyword:$seen' queries for shared mailboxes
  imap/jmap_mail.c
  imap/search_expr.c
Labels: include-in-fastmail

#3540 mboxlist: allow RACL entries where 'l' permission exists
  imap/mboxlist.c
Labels: 3.4, 3.5

#3530 ical_support.c: add missing END:VCALENDAR
  imap/ical_support.c
Labels: include-in-fastmail

#3543 caldav_sched: pass the acting userid through to the imip sender
  imap/http_caldav_sched.c
  imap/http_caldav_sched.h
  imap/http_ischedule.c
Labels: include-in-fastmail

#3555 UUID user_deletedata() fix
  imap/imapd.c
  imap/mailbox.c
  imap/mboxlist.c
  imap/mboxname.c
  imap/mboxname.h
  imap/search_engines.c
  imap/search_engines.h
  imap/search_xapian.c
  imap/sync_reset.c
  imap/sync_support.c
  imap/user.c
  imap/user.h
Labels: include-in-fastmail, include-in-fm-cal2020

#3553 preload string comparisons that will the same for every message
  imap/index.c
Labels: include-in-fastmail, include-in-fm-cal2020

#3556 Memleaks
  imap/caldav_alarm.c
  imap/http_carddav.c
  imap/mailbox.c
  imap/sync_log.c
  imap/sync_support.c
Labels: include-in-fastmail, include-in-fm-cal2020

#3551 jmap_mail: add 'previousCalendarEvent' fetcher
  imap/jmap_mail.c
Labels: include-in-fastmail, include-in-fm-cal2020

#3537 jmap_mail: use custom heuristic for Email.hasAttachment property
  imap/jmap_mail.c
  imap/jmap_mail_query.c
  imap/jmap_mail_query.h
Labels: include-in-fastmail, include-in-fm-cal2020

#3563 Lockfixes
  imap/jmap_mail.c
  imap/mboxlist.c
  imap/mboxname.c
  imap/relocate_by_id.c
Labels: include-in-fastmail, include-in-fm-cal2020

#3522 conversations: cache altrep (uniqueid or name) in the conversations object
  imap/append.c
  imap/conversations.c
  imap/conversations.h
  imap/index.c
  imap/jmap_api.c
  imap/jmap_core.c
  imap/jmap_mail.c
  imap/jmap_mailbox.c
  imap/mailbox.c
  imap/mboxlist.h
  imap/search_xapian.c
Labels: include-in-fastmail, include-in-fm-cal2020

#3566 various memory leak fixes found by valgrinding the cunit tests
  Makefile.am
  cunit/arrayu64.testc
  cunit/bufarray.testc
  cunit/charset.testc
  cunit/dynarray.testc
  cunit/getxstring.testc
  cunit/message.testc
  cunit/procinfo.testc
  cunit/search_expr.testc
  cunit/strarray.testc
  cunit/unit.c
  cunit/vg.supp
  cunit/vparse.testc
  imap/search_expr.c
  lib/libconfig.c
  lib/procinfo.c
  sieve/sieve.y
  sieve/tree.c
Labels: include-in-fastmail

#3573 jmap_mail: load the cache correctly
  imap/jmap_mail.c
Labels: include-in-fastmail, include-in-fm-cal2020
