Repository cyrusimap/cyrus-imapd, pull requests merged in 2022-03, with the labels that each got.

#3922 http_caldav_sched: percent-decode iMIP notification recipient
  cassandane/Cassandane/Cyrus/JMAPCalendars.pm
  cunit/charset.testc
  imap/http_caldav_sched.c
  lib/charset.c
  lib/charset.h
Labels: include-in-fastmail

#3954 jmap_calendar: destroy first, then create events in CalendarEvent/set
  cassandane/Cassandane/Cyrus/JMAPCalendars.pm
  imap/jmap_calendar.c
Labels: include-in-fastmail

#3865 mboxlist: don't truncate over-long mailbox names
  cassandane/Cassandane/Cyrus/Replication.pm
  imap/mailbox.h
  imap/mboxlist.c
  imap/mboxname.c
Labels: include-in-fastmail

#3855 sync_client: in -A mode, reconnect if error
  cassandane/Cassandane/Cyrus/Replication.pm
  cassandane/Cassandane/Cyrus/TestCase.pm
  docsrc/imap/reference/manpages/systemcommands/sync_client.rst
  imap/sync_client.c
  imap/sync_support.c
  imap/sync_support.h
Labels: include-in-fastmail

#3953 http_caldav_sched: only send REPLY for overrides if PARTSTAT differs
  cassandane/Cassandane/Cyrus/JMAPCalendars.pm
  imap/http_caldav_sched.c
Labels: include-in-fastmail

#3951 docs: freshen up jmap implementation status
  docsrc/imap/download/installation/http/jmap.rst
Labels: 3.6

#3958 jmap_calendar: cache recurrence instances in CalendarEvent/get
  imap/jmap_calendar.c
Labels: include-in-fastmail

#3967 ci: Travis to use cyrus-buster instead of cyrus-jessie
  .travis.yml
Labels: 3.6

#3968 cassandane: murder tests require --enable-murder
  cassandane/Cassandane/Cyrus/MurderIMAP.pm
  cassandane/Cassandane/Cyrus/MurderJMAP.pm
Labels: 3.6

#3979 Cassini: check environment for config overrides
  cassandane/Cassandane/Cassini.pm
  cassandane/Cassandane/Test/Cassini.pm
  cassandane/cassandane.ini.example
Labels: 3.0, 3.2, 3.4, 3.6, cassandane

#3987 cassandane: fix up "cleanup" bugs
  cassandane/Cassandane/Cyrus/TestCase.pm
  cassandane/Cassandane/Instance.pm
  cassandane/Cassandane/Unit/TestPlan.pm
Labels: 3.6

#3993 JMAPMailbox: mailbox_counts behaviour change was 3.6
  cassandane/Cassandane/Cyrus/JMAPMailbox.pm
Labels: 3.6

#3999 Cassini: option to permit environment-only config
  cassandane/Cassandane/Cassini.pm
  cassandane/Cassandane/Test/Cassini.pm
  cassandane/cassandane.ini.example
Labels: 3.6
