Repository cyrusimap/cyrus-imapd, pull requests merged in 2022-08, with the labels that each got.

#4186 JMAP upload duplicate content fix
  cassandane/Cassandane/Cyrus/JMAPCore.pm
  cassandane/data/mime/repair_acl.eml
  imap/annotate.c
  imap/http_jmap.c
  imap/mailbox.c
Labels: include-in-fastmail

#4175 jmap_mail: reject control characters in Email headers
  cassandane/tiny-tests/JMAPEmail/email-set-header-control
  imap/jmap_mail.c
Labels: include-in-fastmail

#4180 Reserve mailbox name (mbentry) before mailbox creation
  imap/mailbox.c
  imap/mboxlist.c
Labels: include-in-fastmail

#4188 ctl_cyrusdb -r ("recover") uniqueid safety
  cassandane/Cassandane/Cyrus/CyrusDB.pm
  cassandane/Cassandane/Instance.pm
  imap/ctl_cyrusdb.c
  imap/mailbox.c
  imap/mboxlist.c
  imap/mboxlist.h
  imap/mbpath.c
  perl/imap/Cyrus/DList.pm
  perl/imap/Cyrus/HeaderFile.pm
Labels: backport-to-3.6

#4199 cassandane.ini: don't choke on repeated params
  cassandane/Cassandane/Cassini.pm
  cassandane/cassandane.ini.dockertests
  docsrc/imap/developer/developer-testing.rst
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2

#4197 jmap_mail.c: Email/* should ignore Notes folder
  cassandane/Cassandane/Cyrus/JMAPEmail.pm
  cassandane/tiny-tests/JMAPEmail/email-query-notes
  imap/jmap_mail.c
  imap/search_query.c
Labels: include-in-fastmail

#4203 Move rawquota
  cassandane/Cassandane/Cyrus/Quota.pm
  imap/annotate.c
Labels: include-in-fastmail

#4190 docs: upgrading to 3.6 requires 3.2.10 or 3.4.4 first
  docsrc/imap/download/upgrade.rst
Labels: 3.7

#4215 Cassandane::Util::Log: highlight xlogs starting with XXX
  cassandane/Cassandane/Util/Log.pm
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2
