Repository cyrusimap/cyrus-imapd, pull requests merged in 2022-04, with the labels that each got.

#3995 Sieve include and implicit keep fix
  cassandane/Cassandane/Cyrus/Sieve.pm
  sieve/bc_eval.c
Labels: 3.4, 3.6

#4015 docs: update weekly meeting time
  docsrc/imap/support/feedback-meetings.rst
Labels: 2.5, 3.0, 3.2, 3.4, 3.6

#4020 relocate_by_id fixes
  cassandane/Cassandane/Cyrus/FastMail.pm
  cassandane/Cassandane/Cyrus/RelocateById.pm
  cassandane/Cassandane/Cyrus/SearchSquat.pm
  imap/relocate_by_id.c
Labels: 3.6

#4012 iTIP Reschedule Fix
  cassandane/Cassandane/Cyrus/Sieve.pm
  imap/itip_support.c
Labels: include-in-fastmail

#4030 relocate_by_id: fix typo in initialisation
  imap/relocate_by_id.c
Labels: 3.6

#4000 http_caldav_sched: properties only are equal if parameters match
  cassandane/Cassandane/Cyrus/JMAPCalendars.pm
  imap/http_caldav_sched.c
Labels: include-in-fastmail

#4056 promstatsd: can't accumulate stats from files that couldn't be locked
  imap/promstatsd.c
Labels: 3.6
