Repository cyrusimap/cyrus-imapd, pull requests merged in 2022-05, with the labels that each got.

#4068 imapd: fix cmd_xapplepushservice leak
  imap/imapd.c
Labels: 3.6

#4074 fix 3.6 bare "./configure" build
  Makefile.am
  configure.ac
  imap/mbpath.c
Labels: 3.6

#4076 Support decoding vCard v4 image properties
  cassandane/Cassandane/Cyrus/JMAPContacts.pm
  imap/vcard_support.c
Labels: include-in-fastmail

#4050 jmap_calendars.c: can't free custom timezones until we are doing using them
  cassandane/Cassandane/Cyrus/JMAPCalendars.pm
  imap/jmap_calendar.c
  imap/jmap_ical.c
  imap/jmap_ical.h
Labels: include-in-fastmail

#4052 Sieve include and implicit keep fix (bis)
  cassandane/Cassandane/Cyrus/Sieve.pm
  sieve/bc_eval.c
  sieve/script.c
Labels: include-in-fastmail, 3.4, 3.6

#4018 jmap_mail: implement JMAP "$seen" keyword semantics in Email/query
  cassandane/Cassandane/Cyrus/JMAPEmail.pm
  imap/jmap_mail.c
  imap/search_expr.c
  imap/search_expr.h
Labels: include-in-fastmail

#4031 jmap_calendar: preserve custom timezones in CalendarEvent/set
  cassandane/Cassandane/Cyrus/JMAPCalendars.pm
  imap/jmap_calendar.c
  imap/jmap_ical.c
  imap/jmap_ical.h
Labels: include-in-fastmail

#3351 http_caldav: don't bail for dtstart == dtend
  imap/http_caldav.c
Labels: include-in-fastmail

#4047 Swapping DTEND <-> DURATION shouldn't trigger iTIP
  cassandane/Cassandane/Cyrus/Caldav.pm
  imap/http_caldav_sched.c
Labels: include-in-fastmail

#3981 Jmap blob 09
  cassandane/Cassandane/Cyrus/JMAPCalendars.pm
  cassandane/Cassandane/Cyrus/JMAPContacts.pm
  cassandane/Cassandane/Cyrus/JMAPCore.pm
  cassandane/Cassandane/Cyrus/JMAPEmail.pm
  cassandane/Cassandane/Cyrus/JMAPSieve.pm
  imap/jmap_core.c
Labels: include-in-fastmail, 3.6

#4087 cassandane: verify that smtp service actually started
  cassandane/Cassandane/Instance.pm
  cassandane/Cassandane/PortManager.pm
Labels: 3.4, 3.6, cassandane

#4100 3.4: ensure mbentries have uniqueids
  cassandane/Cassandane/Cyrus/CyrusDB.pm
  cassandane/Cassandane/Cyrus/Reconstruct.pm
  cassandane/Cassandane/Instance.pm
  cassandane/Cyrus/HeaderFile.pm
  imap/ctl_cyrusdb.c
  imap/mailbox.c
  imap/reconstruct.c
Labels: 3.2, 3.4, 3.6

#4096 mboxlist_upgrade() fixes
  imap/mailbox.c
  imap/mailbox.h
  imap/mboxlist.c
Labels: 3.6
