Repository cyrusimap/cyrus-imapd, pull requests merged in 2022-06, with the labels that each got.

#4069 ctl_mboxlist: dump and undump all fields (as JSON)
  cassandane/Cassandane/Cyrus/CtlMboxlist.pm
  cassandane/Cassandane/Cyrus/List.pm
  cassandane/Cassandane/Cyrus/MurderIMAP.pm
  cassandane/Cassandane/Cyrus/TestCase.pm
  cassandane/Cassandane/Instance.pm
  changes/next/ctl_mboxlist_dump
  configure.ac
  docsrc/imap/developer/thoughts/improved_mboxlist_sort.rst
  docsrc/imap/reference/manpages/systemcommands/ctl_mboxlist.rst
  imap/ctl_mboxlist.c
  imap/json_support.c
  imap/json_support.h
  imap/mailbox.c
  imap/mboxlist.h
Labels: 3.2, 3.4, 3.6

#4140 fix assert() definition
  imap/mailbox.c
  imap/message.c
  lib/assert.h
Labels: 3.4, 3.6

#4108 OpenSSL 3.0 fixes
  backup/lcb_append.c
  backup/lcb_internal.h
  backup/lcb_verify.c
  imap/jmap_calendar.c
  imap/tls.c
  imtest/imtest.c
  lib/charset.c
  lib/md5.h
  lib/xsha1.c
  lib/xsha1.h
Labels: include-in-fastmail
