Repository cyrusimap/cyrus-imapd, pull requests merged in 2022-10, with the labels that each got.

#4221 testrunner.pl: exit early if binary components missing
  cassandane/testrunner.pl
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2

#4285 jmap_mail: fix typo in HTML to plain extractor (backport)
  imap/jmap_mail.c
  lib/charset.c
Labels: backport-to-3.2

#4240 index: track changes for modseq bump when setting seen on shared folders
  cassandane/Cassandane/Cyrus/Flags.pm
  imap/index.c
Labels: 3.4, 3.6, backport-to-3.6, backport-to-3.4

#4289 tools/compile_st.pl: strip 'Command-line' from gperf output
  imap/rfc822_header.c
  tools/compile_st.pl
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2
