Repository cyrusimap/cyrus-imapd, pull requests merged in 2023-04, with the labels that each got.

#4428 JMAP Calendar: preserve iCalendar x-properties in updated event
  Makefile.am
  cassandane/tiny-tests/JMAPCalendars/calendarevent_set_preserve_icalxprops
  imap/global.c
  imap/global.h
  imap/httpd.c
  imap/httpd.h
  imap/jcal.c
  imap/jcal.h
  imap/jmap_calendar.c
  imap/jmap_ical.c
  imap/jmap_ical.h
  imap/xcal.c
Labels: include-in-fastmail

#4470 cassandane: add :want_foo magic for per-test configuration of test properties
  cassandane/Cassandane/Cyrus/Sieve.pm
  cassandane/Cassandane/Cyrus/TestCase.pm
  cassandane/testrunner.pl
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8

#4425 charset.c: extract URLs and "alt" text from HTML
  changes/next/charset_extract_html_urls
  cunit/charset.testc
  lib/charset.c
Labels: include-in-fastmail

#4275 http_dav.c, mailbox.c: assert that we have a non-NULL resource (for debugging)
  imap/http_dav.c
  imap/mailbox.c
Labels: include-in-fastmail

#4335 CalendarEvent/participantReply
  cassandane/Cassandane/Cyrus/JMAPCalendars.pm
  cassandane/tiny-tests/JMAPCalendars/calendarevent-participantreply-caldav
  cassandane/tiny-tests/JMAPCalendars/calendarevent-participantreply-simple
  cassandane/tiny-tests/JMAPCalendars/calendarevent-participantreply-standalone
  imap/http_caldav.c
  imap/http_caldav_sched.c
  imap/http_caldav_sched.h
  imap/http_ischedule.c
  imap/ical_support.c
  imap/ical_support.h
  imap/itip_support.c
  imap/itip_support.h
  imap/jmap_backup.c
  imap/jmap_calendar.c
  imap/jmap_ical.c
  imap/jmap_ical.h
  imap/lmtp_sieve.c
Labels: include-in-fastmail

#4419 lmtp_sieve.c: log messages with non-iTIP iCalendar data
  imap/lmtp_sieve.c
Labels: include-in-fastmail

#4485 cassandane: slow test improvements
  cassandane/Cassandane/Cyrus/JMAPBackup.pm
  cassandane/Cassandane/Unit/TestCase.pm
  cassandane/Cassandane/Unit/TestPlan.pm
  cassandane/testrunner.pl
  cassandane/tiny-tests/JMAPCalendars/calendarevent-get-standalone-instances-multi
  cassandane/tiny-tests/JMAPEmail/email-query-cached-evict
Labels: cassandane, backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8
