Repository cyrusimap/cyrus-imapd, pull requests merged in 2023-02, with the labels that each got.

#4396 Html tag colon
  cassandane/Cassandane/Cyrus/SearchFuzzy.pm
  lib/charset.c
Labels: backport-to-3.8

#4382 backend: forward-safe backend_version()
  changes/next/4380-backend-version-bump-watermark
  cunit/backend.testc
  imap/backend.c
  imap/mailbox.h
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8

#4400 jmap_ical.c: don't add RECURRENCE-ID property for recurrenceId:null
  imap/jmap_ical.c
Labels: backport-to-3.8

#4401 Jmap move deleted parent
  cassandane/Cassandane/Cyrus/JMAPMailbox.pm
  imap/jmap_api.c
Labels: include-in-fastmail, backport-to-3.6, backport-to-3.8

#3781 Annotatemore mboxname
  imap/annotate.c
  imap/annotate.h
  imap/jmap_backup.c
  imap/sync_support.c
Labels: backport-to-3.8

#4397 JMAP Calendars: always guess IANA timezone id
  cassandane/data/icalendar/orphaned-timezones.ics
  cassandane/tiny-tests/JMAPCalendars/calendarevent-get-custom-timezones-orphans
  cassandane/tiny-tests/JMAPCalendars/calendarevent-guesstz
  cassandane/tiny-tests/JMAPCalendars/calendarevent-guesstz-gmt
  cassandane/tiny-tests/JMAPCalendars/calendarevent-guesstz-recur
  cassandane/tiny-tests/JMAPCalendars/calendarevent-query-custom-timezones
  cassandane/tiny-tests/JMAPCalendars/calendarevent-set-custom-timezones
  cassandane/tiny-tests/JMAPCalendars/calendarevent-set-custom-timezones-orphans
  cassandane/tiny-tests/JMAPCalendars/calendarevent_guesstz_etc_gmt
  cassandane/tiny-tests/JMAPCalendars/calendarevent_guesstz_ignore_xjmapid
  imap/jmap_calendar.c
  imap/jmap_ical.c
  imap/jmap_ical.h
Labels: include-in-fastmail

#4402 Append fixes
  imap/append.c
  lib/map_shared.c
Labels: include-in-fastmail

#4404 docs: fix doc build errors from typos
  docsrc/imap/download/installation/http/caldav.rst
  docsrc/imap/reference/manpages/systemcommands/jmap_expire.rst
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8

#4415 user_sieve_path(): never return "" -- always return a sensible path
  imap/user.c
Labels: backport-to-3.8
