Repository cyrusimap/cyrus-imapd, pull requests merged in 2023-11, with the labels that each got.

#4683 ical_support: configure libical to omit CONTROL characters
  cassandane/Cassandane/Cyrus/Caldav.pm
  configure.ac
  imap/cyr_buildinfo.c
  imap/ical_support.c
Labels: include-in-fastmail

#4712 Subscriptions bump folderstate
  cassandane/Cassandane/Cyrus/JMAPMailbox.pm
  imap/jmap_mailbox.c
  imap/mboxlist.c
Labels: include-in-fastmail

#4710 fix userflags corruption crash
  cassandane/Cassandane/Cyrus/Flags.pm
  imap/mailbox.c
  lib/xmalloc.h
Labels: backport-to-3.6, backport-to-3.8

#4724 fixes found by gcc static analyzer
  backup/ctl_backups.c
  com_err/et/init_et.c
  cunit/annotate.testc
  cunit/http_jwt.testc
  imap/annotate.c
  imap/ctl_mboxlist.c
  imap/cyr_virusscan.c
  imap/dav_util.c
  imap/http_caldav.c
  imap/http_dav.c
  imap/http_dav_sharing.c
  imap/index.c
  imap/jmap_sieve.c
  imap/lmtpd.c
  imap/mailbox.c
  imap/mboxevent.c
  imap/nntpd.c
  imap/prometheus.c
  imap/promstatsd.c
  imap/search_xapian.c
  sieve/message.c
Labels: include-in-fastmail

#4737 github-actions: report debian version
  .github/workflows/main.yml
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8

#4736 add pcre2 support
  changes/next/pcre2-support
  configure.ac
  docsrc/assets/cyrus-build-devpkg.rst
  docsrc/assets/cyrus-build-reqpkg.rst
  docsrc/imap/developer/compiling.rst
  docsrc/imap/download/upgrade.rst
  imap/cyr_buildinfo.c
  lib/util.h
  ptclient/test3.c
  sieve/bc_eval.c
  sieve/comparator.h
  sieve/sieve.y
Labels: include-in-fastmail, backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8

#4741 fix pcre2 crash when regex_t uninitialised
  cassandane/Cassandane/Cyrus/Sieve.pm
  cunit/buf.testc
  lib/glob.c
  sieve/sieve.y
Labels: include-in-fastmail, backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8

#4746 DAV propfind: don't crash if we fail to transform iCal/vCard data
  imap/http_dav.c
  imap/http_err.et
  imap/ical_support.c
  imap/vcard_support.c
Labels: include-in-fastmail

#4747 vcard_support.c: handle data: URIs even if VALUE=X
  cassandane/tiny-tests/JMAPContacts/card-get-v4
  imap/vcard_support.c
Labels: include-in-fastmail

#4743 pop3d: try to not split ".\r\n" across packet boundary
  imap/pop3d.c
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8, backport-to-3.10

#4749 glob: fix missing include
  lib/glob.c
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8, backport-to-3.10
