Repository cyrusimap/cyrus-imapd, pull requests merged in 2023-09, with the labels that each got.

#4633 fix FETCH BINARY response for unknown CTE
  cassandane/Cassandane/Cyrus/Fetch.pm
  imap/index.c
  imap/index.h
Labels: backport-to-3.8

#4603 JMAP Email: ignore NUL bytes in Email/get bodyValues
  cassandane/tiny-tests/JMAPEmail/email_get_bodyvalues_crlf
  cassandane/tiny-tests/JMAPEmail/email_get_bodyvalues_nulbyte
  cunit/charset.testc
  imap/cyr_ls.c
  imap/http_rss.c
  imap/index.c
  imap/jmap_mail.c
  imap/jmap_mailbox.c
  imap/jmap_notes.c
  imap/jmap_util.c
  imap/jmap_util.h
  imap/mboxname.c
  imap/message.c
  lib/charset.c
  lib/charset.h
Labels: include-in-fastmail

#4578 conversations: sort thread by createdmodseq if same internaldate
  cassandane/tiny-tests/JMAPEmail/email_get_createdmodseq
  imap/conversations.c
  imap/conversations.h
  imap/jmap_mail.c
Labels: include-in-fastmail

#4639 Update 3.6.0 release notes
  docsrc/imap/download/release-notes/3.6/x/3.6.0-beta1.rst
  docsrc/imap/download/release-notes/3.6/x/3.6.0-beta2.rst
  docsrc/imap/download/release-notes/3.6/x/3.6.0-beta3.rst
  docsrc/imap/download/release-notes/3.6/x/3.6.0-rc1.rst
  docsrc/imap/download/release-notes/3.6/x/3.6.0-rc2.rst
  docsrc/imap/download/release-notes/3.6/x/3.6.0.rst
  docsrc/imap/rfc-support.rst
Labels: backport-to-3.6, backport-to-3.8

#4651 cyr_info BYTESIZE suppport
  cassandane/Cassandane/Config.pm
  cassandane/Cassandane/Cyrus/Info.pm
  imap/cyr_info.c
Labels: backport-to-3.8

#4637 admin/sieve.rst: update on former drafts
  docsrc/imap/reference/admin/sieve.rst
Labels: 3.4

#4658 github actions: report cyr_buildinfo details
  .github/workflows/main.yml
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8
