Repository cyrusimap/cyrus-imapd, pull requests merged in 2023-10, with the labels that each got.

#4679 docs: we don't support Link Time Optimization
  docsrc/imap/developer/compiling.rst
Labels: backport-to-3.8

#4678 various squat fixes
  cassandane/Cassandane/Cyrus/SearchSquat.pm
  cassandane/Cassandane/Cyrus/TestCase.pm
  changes/next/4660-squatdb-fixes
  imap/search_engines.h
  imap/search_squat.c
  imap/squat_build.c
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8

#4698 search_query: fix filtering unindexed messages in squat backend
  cassandane/Cassandane/Cyrus/SearchSquat.pm
  imap/search_query.c
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8

#4686 bookworm fixes
  cassandane/Cassandane/Cyrus/Annotator.pm
  cassandane/Cassandane/Cyrus/Conversations.pm
  cassandane/Cassandane/Cyrus/JMAPMailbox.pm
  cassandane/Cassandane/Cyrus/JMAPTestSuiteWS.pm
  cassandane/Cassandane/Cyrus/SearchSquat.pm
  cassandane/Cassandane/IMAPMessageStore.pm
  cassandane/Cassandane/Instance.pm
  cassandane/Cassandane/Util/Log.pm
  cassandane/tiny-tests/JMAPEmail/email-set-update-too-many-mailboxes-lowlimit
  docsrc/imap/developer/developer-testing.rst
  imap/conversations.c
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8

#4706 Convdb zero singlecid
  cassandane/Cassandane/Cyrus/Conversations.pm
  docsrc/imap/reference/manpages/systemcommands/ctl_conversationsdb.rst
  imap/ctl_conversationsdb.c
Labels: include-in-fastmail
