Repository cyrusimap/cyrus-imapd, pull requests merged in 2023-03, with the labels that each got.

#4412 fix bare configure build
  cassandane/Cassandane/Cyrus/Conversations.pm
  cassandane/Cassandane/Cyrus/FastMail.pm
  cassandane/Cassandane/Cyrus/Idle.pm
  cassandane/Cassandane/Cyrus/Metadata.pm
  cassandane/Cassandane/Cyrus/Quota.pm
  cassandane/Cassandane/Cyrus/Rename.pm
  cassandane/Cassandane/Cyrus/Replication.pm
  cassandane/Cassandane/Cyrus/Sieve.pm
  configure.ac
  imap/caldav_util.h
  imap/dav_util.c
  imap/dav_util.h
  imap/itip_support.c
  imap/jmap_notif.c
  imap/jmap_util.c
  imap/jmap_util.h
  imap/mboxname.c
Labels: backport-to-3.8

#4437 http_dav.c: Can't check mailbox type when proxying PUT
  cassandane/Cassandane/Cyrus/MurderDAV.pm
  imap/http_dav.c
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.8

#4447 IMAP::Shell: fix uninitialized value warning
  perl/imap/IMAP/Shell.pm
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8

#4452 bc_eval.c another local time fix (local offset changes with DST - duh!)
  cassandane/Cassandane/Cyrus/Sieve.pm
  sieve/bc_eval.c
Labels: include-in-fastmail
