Repository cyrusimap/cyrus-imapd, pull requests merged in 2023-05, with the labels that each got.

#4463 JMAPTestSuite: Email:import behaviour changed in 3.8+
  cassandane/Cassandane/Cyrus/JMAPTestSuite.pm
  cassandane/Cassandane/Cyrus/JMAPTestSuiteWS.pm
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8

#4497 lmtpd.c: internalseen is determined by the owner of the Sieve script
  cassandane/Cassandane/Cyrus/Sieve.pm
  imap/lmtpd.c
Labels: backport-to-3.8

#4501 github actions: workaround "dubious ownership" failures
  .github/workflows/main.yml
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8

#4507 developer-testing.rst: explain CI imaptest setup
  docsrc/imap/developer/developer-testing.rst
Labels: documentation, backport-to-3.8

#4510 Simple: add tests for APPENDLIMIT capability
  cassandane/Cassandane/Cyrus/Simple.pm
Labels: backport-to-3.8

#4511 http_dav: fix meth_mkcol leak when mailbox is remote
  imap/http_dav.c
Labels: backport-to-3.8

#4513 docs: remove references to jmap_guesstz_fname
  docsrc/imap/download/release-notes/3.8/x/3.8.0-beta1.rst
  docsrc/imap/download/release-notes/3.8/x/3.8.0-beta2.rst
  docsrc/imap/download/release-notes/3.8/x/3.8.0-rc1.rst
  docsrc/imap/download/release-notes/3.8/x/3.8.0.rst
Labels: backport-to-3.8

#4348 github actions: split cass run into several steps
  .github/workflows/main.yml
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8

#4514 Require libical >= 3.0.10
  changes/next/require_libical_3.0.10
  configure.ac
  imap/ical_support.c
  imap/ical_support.h
Labels: 3.8, 3.9, backport-to-3.8
