Repository cyrusimap/cyrus-imapd, pull requests merged in 2023-01, with the labels that each got.

#4347 Cyrus 3.8: http_caldav: allow CalDAV alarms on calendar home
  cassandane/Cassandane/Cyrus/Caldav.pm
  imap/caldav_alarm.c
  imap/caldav_util.c
  imap/http_caldav.c
Labels: 3.8

#4354 iCalendar properties -> MIME header fixes
  cassandane/Cassandane/Cyrus/Caldav.pm
  cassandane/Cassandane/Cyrus/Sieve.pm
  imap/caldav_util.c
  imap/itip_support.c
Labels: include-in-fastmail

#4366 backend: update backend_version() for 3.8 and 3.9
  cunit/backend.testc
  imap/backend.c
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8

#4342 CaldavAlarm: fix inf loop in test_disable_high_freq
  cassandane/Cassandane/Cyrus/CaldavAlarm.pm
Labels: backport-to-3.8

#4372 docs: fix typo
  docsrc/imap/download/release-notes/3.8/x/3.8.0-alpha0.rst
Labels: backport-to-3.8

#4352 GitHub CI status badge
  README.md
  docsrc/conf.py
  docsrc/exts/themes/cyrus/buildstatus.html
  docsrc/exts/themes/cyrus/theme.conf
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8

#4378 imapd.c: fix list_data_remote() string arrays to match bitmasks
  imap/imapd.c
Labels: backport-to-3.8

#4381 Sieve: test_notify() works as far back as 3.2
  cassandane/Cassandane/Cyrus/Sieve.pm
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.8

#4391 Rename.pm: test renaming a user who has had mailboxes shared to them
  cassandane/Cassandane/Cyrus/Rename.pm
Labels: backport-to-3.6, backport-to-3.8

#4345 jmap_api: refactor JMAP state API to jmap_modseq function
  imap/jmap_api.c
  imap/jmap_api.h
  imap/jmap_calendar.c
  imap/jmap_contact.c
  imap/jmap_mail.c
  imap/jmap_mail_submission.c
  imap/jmap_mailbox.c
  lib/util.c
  lib/util.h
Labels: include-in-fastmail

#4034 Expire JMAP notifications using jmap_expire
  .gitignore
  Makefile.am
  changes/next/cyr_expire_jmap
  doc/examples/cyrus_conf/normal-master.conf
  doc/examples/cyrus_conf/normal-replica.conf
  doc/examples/cyrus_conf/normal.conf
  doc/examples/cyrus_conf/small.conf
  docsrc/imap/reference/manpages/systemcommands/jmap_expire.rst
  imap/cyr_expire.c
  imap/cyr_virusscan.c
  imap/ipurge.c
  imap/jmap_calendar.c
  imap/jmap_expire.c
  imap/mailbox.c
  imap/mailbox.h
Labels: include-in-fastmail

#4359 Lock ordering fixes
  cassandane/Cassandane/Cyrus/Expunge.pm
  imap/conversations.c
  imap/imapd.c
  imap/index.c
  imap/jmap_backup.c
  imap/mailbox.c
  imap/mboxlist.c
  imap/search_query.c
  imap/search_query.h
  imap/sieve_db.c
Labels: include-in-fastmail, backport-to-3.8

#4395 Fix iter-startuid off by one issue
  imap/index.c
  imap/mailbox.c
Labels: backport-to-3.6, backport-to-3.8

#4383 rolling squatter: compact databases
  imap/squatter.c
Labels: backport-to-3.6, backport-to-3.8
