Repository cyrusimap/cyrus-imapd, pull requests merged in 2023-12, with the labels that each got.

#4756 message: fix uninitialized access in extract_convdata
  cassandane/Cassandane/Cyrus/Sieve.pm
  imap/message.c
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8

#4759 docs: coverage reports
  docsrc/imap/developer.rst
  docsrc/imap/developer/coverage.rst
Labels: backport-to-3.8

#4748 vCard: strip any X-LIC-ERR properties
  imap/http_carddav.c
  imap/index.c
  imap/vcard_support.c
Labels: include-in-fastmail

#4742 Remove jmap_expire and automatically prune calendareventnotifs
  .gitignore
  Makefile.am
  cassandane/Cassandane/Cyrus/TestCase.pm
  cassandane/tiny-tests/JMAPCalendars/calendareventnotification-prune
  changes/next/cyr_expire_jmap
  changes/next/prune_calendareventnotifs
  doc/examples/cyrus_conf/normal-master.conf
  doc/examples/cyrus_conf/normal-replica.conf
  doc/examples/cyrus_conf/normal.conf
  doc/examples/cyrus_conf/small.conf
  docsrc/imap/reference/manpages/systemcommands/jmap_expire.rst
  imap/jmap_expire.c
  imap/jmap_notif.c
  lib/imapoptions
Labels: include-in-fastmail, backport-to-3.10
