Repository cyrusimap/cyrus-imapd, pull requests merged in 2024-06, with the labels that each got.

#4827 cyr_expire: silent delete for cleaning up DELETED mailboxes
  imap/annotate.c
  imap/cyr_expire.c
  imap/quota.c
  imap/sync_support.c
Labels: include-in-fastmail, backport-to-3.10

#4900 JMAP Calendars: support vendor-extension properties in VirtualLocations
  cassandane/tiny-tests/JMAPCalendars/calendarevent_set_fullblown
  cassandane/tiny-tests/JMAPCalendars/calendarevent_set_virtuallocation_xprop
  imap/ical_support.c
  imap/ical_support.h
  imap/jmap_ical.c
  imap/jmap_ical.h
Labels: include-in-fastmail

#4917 caldav_alarm: suppress duplicate alarms
  cassandane/tiny-tests/CaldavAlarm/suppress_duplicates
  changes/next/calalarmd_suppress_duplicates
  cunit/ical_support.testc
  imap/caldav_alarm.c
  imap/ical_support.c
  lib/imapoptions
Labels: include-in-fastmail

#4924 imapd.c: remove support for XMOVE
  changes/next/remove_imap_xmove
  imap/imapd.c
  imap/imapd.h
Labels: include-in-fastmail

#4929 github actions: finesse triggers, update actions/checkout
  .github/workflows/main.yml
  docsrc/imap/developer/major-releasing.rst
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8, backport-to-3.10

#4940 github actions on forks
  .github/workflows/main.yml
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8, backport-to-3.10

#4937 imapparse: accept client LITERAL+ for mupdate
  cassandane/Cassandane/Instance.pm
  imap/imapparse.c
  imap/imapparse.h
  imap/mupdate-client.c
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.8, backport-to-3.10
