Repository cyrusimap/cyrus-imapd, pull requests merged in 2024-03, with the labels that each got.

#4826 sync_support: duplicate the sieve script
  imap/sync_support.c
Labels: include-in-fastmail

#4828 http_carddav.c: Don't allow the Default addressbook to be deleted
  cassandane/Cassandane/Cyrus/Carddav.pm
  imap/http_carddav.c
Labels: backport-to-3.6, backport-to-3.8, backport-to-3.10

#4825 search_query.c: min_uid might start at zero
  imap/search_query.c
Labels: include-in-fastmail, backport-to-3.6, backport-to-3.8, backport-to-3.10

#4822 rename mboxlist_sync_setacls to mboxlist_setacls and add silent flag
  imap/http_dav.c
  imap/http_jmap.c
  imap/jmap_api.c
  imap/mboxlist.c
  imap/mboxlist.h
  imap/sync_support.c
Labels: include-in-fastmail

#4782 xapian_wrap.cpp: query verbatim for terms using fullwidth form
  cassandane/tiny-tests/JMAPEmail/email_query_cjk_fullwidth
  imap/xapian_wrap.cpp
Labels: include-in-fastmail

#4840 Mmap null
  lib/map_nommap.c
  lib/map_shared.c
  lib/map_stupidshared.c
Labels: include-in-fastmail

#4846 annotate_state_writemdata: only called from sync_server, make silent
  imap/annotate.c
  imap/mbdump.c
  imap/mboxlist.c
  imap/mboxlist.h
  imap/sync_support.c
Labels: include-in-fastmail

#4844 Plug some Sieve leaks
  cassandane/tiny-tests/Sieve/enotify
  imap/sync_support.c
  sieve/sieve.y
Labels: include-in-fastmail

#4831 Parse email addresses with non-ASCII UTF8 domain parts
  cassandane/data/mime/utf8-domain.bin
  cassandane/tiny-tests/JMAPEmail/email_get_utf8_domain
  changes/next/parseaddr_utf8_domain
  cunit/parseaddr.testc
  imap/mailbox.h
  lib/parseaddr.c
Labels: include-in-fastmail

#4851 conversations: don't update xconvmodseq on replicas
  cunit/conversations.testc
  imap/conversations.c
  imap/conversations.h
  imap/mailbox.c
Labels: include-in-fastmail

#4852 Sync user repair
  cassandane/Cassandane/Cyrus/Replication.pm
  cassandane/tiny-tests/Replication/full_rename
  imap/sync_support.c
  imap/sync_support.h
Labels: include-in-fastmail

#4834 imapd.c: add support for JMAPACCESS capability and response code
  changes/next/imap_jmapaccess
  docsrc/imap/rfc-support.rst
  imap/imapd.c
  lib/imapoptions
Labels: include-in-fastmail

#4867 Replicaonly reset
  imap/mailbox.c
  imap/mboxlist.c
  imap/mboxlist.h
  imap/sync_reset.c
Labels: include-in-fastmail
