Repository cyrusimap/cyrus-imapd, pull requests merged in 2024-01, with the labels that each got.

#4780 SearchFuzzy.pm: do not use non-standard XSNIPPETS command
  cassandane/Cassandane/Cyrus/SearchFuzzy.pm
Labels: include-in-fastmail

#4776 message.c: only attempt to read first Received header date
  cunit/message.testc
  imap/message.c
Labels: include-in-fastmail

#4725 defaultalarms: ignore user alerts if useDefaultAlerts=true
  cassandane/Cassandane/Cyrus/Caldav.pm
  cassandane/data/icalendar/alerts.ics
  cassandane/tiny-tests/JMAPCalendars/admin-migrate39-defaultalerts
  cassandane/tiny-tests/JMAPCalendars/calendarevent-defaultalerts-calalarmd
  cassandane/tiny-tests/JMAPCalendars/calendarevent-defaultalerts-updated-by-caldav-put
  cassandane/tiny-tests/JMAPCalendars/calendarevent-get-alerts
  imap/caldav_alarm.c
  imap/defaultalarms.c
  imap/defaultalarms.h
  imap/http_caldav.c
  imap/ical_support.c
  imap/ical_support.h
  imap/itip_support.c
Labels: include-in-fastmail

#4779 jmap_mail_submission.c: properly handle onSuccessDestroyEmail:null
  cassandane/Cassandane/Cyrus/JMAPEmailSubmission.pm
  imap/jmap_mail_submission.c
Labels: include-in-fastmail

#4775 imapd.c: add a couple of capabilities in EXTRA WGLC
  imap/imapd.c
Labels: Do Not Merge

#4750 runtime toggleable debug logging
  cassandane/Cassandane/Cyrus/Simple.pm
  cassandane/utils/syslog.c
  changes/next/toggleable-debug
  imap/global.c
  imap/imapd.c
  lib/imapoptions
  lib/libconfig.c
  lib/libconfig.h
  lib/signals.c
Labels: Do Not Merge, include-in-fastmail

#4788 jmap_contact.c: tweak street building in jmap_contact_from_vcard()
  imap/jmap_contact.c
Labels: 3.8

#4801 github actions: increase cassandane job count
  .github/workflows/main.yml
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8, backport-to-3.10
