Repository cyrusimap/cyrus-imapd, pull requests merged in 2024-09, with the labels that each got.

#4988 message.c: fix reading cached bodystructure for "message/global"
  imap/message.c
Labels: include-in-fastmail

#5011 TestPlan: check for bad/orphaned tiny-tests
  cassandane/Cassandane/Unit/TestPlan.pm
  cassandane/testrunner.pl
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8, backport-to-3.10

#3368 3.2 - Sieve "include": :once and :optional flags in bytecode were being parsed in reverse
  sieve/bytecode.h
  sieve/sieved.c
Labels: backport-to-3.2

#5023 jmap_email.c: refactor Email/copy to use _email_bulkupdate
  cassandane/tiny-tests/JMAPEmail/email_copy
  imap/jmap_api.c
  imap/jmap_api.h
  imap/jmap_mail.c
Labels: include-in-fastmail

#5038 Makefile.am: 4-space indents, except where we can't
  Makefile.am
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8, backport-to-3.10

#5017 Resolve clang-tidy warnings for Xapian wrapper
  imap/index.c
  imap/jmap_mail.c
  imap/jmap_mail_query.c
  imap/search_engines.c
  imap/search_engines.h
  imap/search_expr.h
  imap/search_part.h
  imap/search_squat.c
  imap/search_xapian.c
  imap/xapian_wrap.cpp
  imap/xapian_wrap.h
Labels: include-in-fastmail

#5016 message.c: only read message/global envelope if cache version >= 13
  imap/message.c
Labels: include-in-fastmail

#5015 caldav_alarm: support suppressing alarms for VEVENT or VTODO
  cassandane/Cassandane/Cyrus/TestCase.pm
  cassandane/tiny-tests/CaldavAlarm/supported_components
  changes/next/caldav_alarm_supported_components
  imap/caldav_alarm.c
  lib/imapoptions
Labels: include-in-fastmail

#5032 Lmtp ratelimit
  changes/next/lmtp-ratelimit
  imap/imap_err.et
  imap/imapd.c
  imap/lmtp_err.et
  imap/lmtpd.c
  imap/lmtpengine.c
  imap/nntpd.c
  imap/pop3d.c
  lib/proc.c
  lib/proc.h
Labels: include-in-fastmail

#5036 Master babysit retry
  cassandane/Cassandane/Cyrus/Master.pm
  changes/next/master-babysit-retry
  master/master.c
Labels: include-in-fastmail

#5052 http_caldav_sched.c:imip_send_sendmail() - do not send lonely LF
  imap/http_caldav_sched.c
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8, backport-to-3.10
