Repository cyrusimap/cyrus-imapd, pull requests merged in 2024-10, with the labels that each got.

#4143 Update compiling.rst
  docsrc/imap/developer/compiling.rst
Labels: backport-to-3.8, backport-to-3.10

#5077 rfc-support.rst: clarify for Lemonade that NOTIFY is not missing
  docsrc/imap/rfc-support.rst
Labels: backport-to-3.10

#5065 http_caldav.c: do not require tzdist module for calendar-timezone-id
  cassandane/tiny-tests/Caldav/rfc7898_calendar_timezone_id
  changes/next/http_caldav_proppatch_timezone_id
  imap/http_caldav.c
Labels: include-in-fastmail

#5058 message.c: parse unbracketed dot-atom-text message-ids
  cassandane/tiny-tests/JMAPEmail/thread_get_nobracket_message_id
  cunit/message_iter_msgid.testc
  imap/index.c
  imap/message.c
  imap/message.h
Labels: include-in-fastmail
