Repository cyrusimap/cyrus-imapd, pull requests merged in 2024-02, with the labels that each got.

#4731 Mailbox locking refcount
  cassandane/Cassandane/Cyrus/JMAPMailbox.pm
  cassandane/Cassandane/Cyrus/Reconstruct.pm
  cassandane/Cassandane/Cyrus/Replication.pm
  cassandane/Cassandane/Instance.pm
  cassandane/doc/README.deps
  cassandane/tiny-tests/JMAPCalendars/calendar-set-sharewith-acl
  imap/autocreate.c
  imap/dlist.c
  imap/dlist.h
  imap/http_dav.c
  imap/http_dav_sharing.c
  imap/http_dav_sharing.h
  imap/http_jmap.c
  imap/imapd.c
  imap/jmap_api.c
  imap/jmap_api.h
  imap/jmap_backup.c
  imap/jmap_calendar.c
  imap/jmap_contact.c
  imap/jmap_core.c
  imap/jmap_ical.c
  imap/jmap_mail.c
  imap/jmap_mail_submission.c
  imap/jmap_mailbox.c
  imap/jmap_mdn.c
  imap/jmap_notes.c
  imap/jmap_sieve.c
  imap/lmtp_sieve.c
  imap/mailbox.c
  imap/mailbox.h
  imap/mboxlist.c
  imap/mboxlist.h
  imap/mboxname.c
  imap/reconstruct.c
  imap/sync_reset.c
  imap/sync_support.c
  imap/user.c
Labels: include-in-fastmail

#4744 Global lock
  .gitignore
  Makefile.am
  changes/next/global-lock
  docsrc/imap/reference/manpages/systemcommands/cyr_withlock_run.rst
  imap/cyr_withlock_run.c
  imap/global.c
  imap/global.h
  imap/mboxname.c
  imap/mboxname.h
  imap/user.c
  imap/user.h
  lib/command.c
  lib/command.h
  lib/imapoptions
Labels: include-in-fastmail

#4758 Rename between users
  cassandane/Cassandane/Cyrus/Conversations.pm
  cassandane/Cassandane/Cyrus/Quota.pm
  imap/conversations.c
  imap/mailbox.c
  imap/mailbox.h
  imap/mboxlist.c
Labels: include-in-fastmail, backport-to-3.6, backport-to-3.8, backport-to-3.10

#4721 Calalarmd replicaonly
  cassandane/Cassandane/Cyrus/CaldavAlarm.pm
  cassandane/Cassandane/Cyrus/Replication.pm
  cassandane/Cassandane/Cyrus/TestCase.pm
  changes/next/replicaonly
  imap/calalarmd.c
  imap/caldav_alarm.c
  imap/mboxname.c
  imap/user.c
  imap/user.h
  lib/imapoptions
Labels: include-in-fastmail, backport-to-3.10

#4807 jmap_api.c: ignore rights on \Scheduled when adjusting #jmap
  cassandane/Cassandane/Cyrus/JMAPMailbox.pm
  imap/jmap_api.c
Labels: include-in-fastmail

#4804 mailbox: fix mailbox_maxmessages checks
  cassandane/Cassandane/Cyrus/Caldav.pm
  cassandane/Cassandane/Cyrus/Carddav.pm
  cassandane/Cassandane/Cyrus/MaxMessages.pm
  imap/mailbox.c
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.8, backport-to-3.10

#4811 replicaonly: add silent RACL updates and batch them to sync
  imap/cyr_expire.c
  imap/mboxlist.c
  imap/mboxlist.h
  imap/mboxname.c
  imap/mboxname.h
  imap/sync_reset.c
  imap/sync_support.c
Labels: include-in-fastmail, backport-to-3.10

#4806 re-fix filtering unindexed messages in squat backend
  cassandane/Cassandane/Cyrus/SearchSquat.pm
  imap/search_expr.c
  imap/search_expr.h
  imap/search_query.c
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.8, backport-to-3.10

#4819 Revert "tls.c: need to free SSL_SESSION when removing it from cache"
  imap/tls.c
Labels: backport-to-3.8, backport-to-3.10
