Repository cyrusimap/cyrus-imapd, pull requests merged in 2024-07, with the labels that each got.

#4958 sync_sieve_upload() always initialize buffer with script content
  imap/sync_support.c
Labels: backport-to-3.6, backport-to-3.8, backport-to-3.10

#4948 configure.ac: replication is not 'experimental'
  configure.ac
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.8, backport-to-3.10

#4962 jmap_contact.c: support X-PHONETIC extension properties
  cassandane/tiny-tests/JMAPContacts/contact_copy_phonetic
  cassandane/tiny-tests/JMAPContacts/contact_get_phonetic
  cassandane/tiny-tests/JMAPContacts/contact_set_phonetic
  imap/jmap_contact.c
Labels: include-in-fastmail

#4906 vCard: add support for libicalvcard vcardcomponent_transform()
  cassandane/tiny-tests/Carddav/bulk_import_export
  cassandane/tiny-tests/Carddav/put_get_v3_v4
  cassandane/tiny-tests/JMAPContacts/card_get_v4
  cassandane/tiny-tests/JMAPContacts/card_set_create_anniversaries
  imap/http_carddav.c
  imap/vcard_support.c
  imap/vcard_support.h
Labels: include-in-fastmail

#4979 sync_support: copy_remote speedup
  imap/sync_support.c
Labels: include-in-fastmail

#4980 fix imapd capabilities crash when built with source fortification
  cassandane/Cassandane/Cyrus/CyrusDB.pm
  cassandane/Cassandane/Cyrus/Delivery.pm
  cassandane/Cassandane/Cyrus/Reconstruct.pm
  cassandane/Cassandane/Instance.pm
  cassandane/tiny-tests/JMAPEmail/searchsnippet_search_maxsize
  cassandane/tiny-tests/SearchFuzzy/squatter_attachextract_nolock
  cassandane/utils/syslog_probe.c
  imap/cyr_buildinfo.c
  imap/http_h2.c
  imap/httpd.c
  imap/imapd.c
  imap/jmap_calendar.c
  imap/mbexamine.c
  imap/vcard_support.c
Labels: backport-to-3.10

#4982 annotate: don't re-read mbentry every time if mailbox is open
  imap/annotate.c
  imap/mailbox.c
  imap/mailbox.h
Labels: include-in-fastmail

#4954 vcard_support.c: properly handle X-APPLE-OMIT-YEAR parameter
  cassandane/cassandane/tiny-tests/Carddav/put_bday_noyear
  cassandane/cassandane/tiny-tests/JMAPContacts/card_set_create_bday_noyear
  cassandane/cassandane/tiny-tests/JMAPContacts/contact_set_create_bday_noyear
Labels: include-in-fastmail

#4925 imapd.c: remove support for SCAN command
  cassandane/tiny-tests/List/scan
  imap/imapd.c
  imap/imapd.h
  imap/index.c
  imap/index.h
Labels: include-in-fastmail

#4926 Improve handling of 8bit message content and `message/global`
  Makefile.am
  cassandane/Cassandane/Cyrus/SearchFuzzy.pm
  cassandane/Cassandane/Instance.pm
  cassandane/tiny-tests/JMAPEmail/email_blob_set_singlecommand
  cassandane/tiny-tests/JMAPEmail/email_get_encoded_message
  cassandane/tiny-tests/JMAPEmail/email_get_header_nfc
  cassandane/tiny-tests/JMAPEmail/email_query_attachmentname
  cassandane/tiny-tests/JMAPEmail/email_query_attachments
  cassandane/tiny-tests/JMAPEmail/email_query_emailaddress
  cassandane/tiny-tests/JMAPEmail/email_query_messageid
  cassandane/tiny-tests/JMAPEmail/email_query_references_inreplyto
  cassandane/tiny-tests/JMAPEmail/email_set_blobencoding
  cassandane/tiny-tests/JMAPEmail/email_set_bodystructure
  cassandane/tiny-tests/JMAPEmail/email_set_create_encoding
  cassandane/tiny-tests/JMAPEmail/email_set_create_no_xmailer_header
  cassandane/tiny-tests/JMAPEmail/email_set_encode_plain_text_attachment
  cassandane/tiny-tests/JMAPEmail/email_set_header_nfc
  cassandane/tiny-tests/JMAPEmail/email_set_location
  cassandane/tiny-tests/JMAPEmail/email_set_text_crlf
  cassandane/tiny-tests/JMAPEmail/misc_upload_bin
  changes/next/xapian_add_messageid
  cunit/message_iter_msgid.testc
  imap/caldav_util.c
  imap/carddav_db.c
  imap/global.c
  imap/global.h
  imap/http_carddav.c
  imap/http_jmap.c
  imap/index.c
  imap/jmap_ical.c
  imap/jmap_mail.c
  imap/jmap_mail_query.c
  imap/jmap_mail_query_parse.c
  imap/jmap_util.c
  imap/mailbox.h
  imap/message.c
  imap/message.h
  imap/message_guid.h
  imap/search_engines.c
  imap/search_engines.h
  imap/search_part.h
  imap/search_xapian.c
  imap/xapian_wrap.cpp
  imap/xapian_wrap.h
  lib/charset.c
  lib/charset.h
  lib/libcyr_cfg.c
  perl/sieve/managesieve/Makefile.PL.in
Labels: include-in-fastmail

#4865 Group racl
  cassandane/Cassandane/Cyrus/HTTPPTS.pm
  cassandane/Cassandane/Cyrus/LDAP.pm
  cassandane/Cassandane/IMAPMessageStore.pm
  cassandane/data/directory.ldif
  cassandane/tiny-tests/FastMail/touch_raclmodseq
  changes/next/groupracl
  docsrc/imap/reference/manpages/systemcommands/ptexpire.rst
  imap/imapd.c
  imap/mboxlist.c
  imap/mboxlist.h
  lib/imapoptions
  ptclient/http.c
  ptclient/ldap.c
  ptclient/ptexpire.c
Labels: include-in-fastmail
