Repository cyrusimap/cyrus-imapd, pull requests merged in 2024-11, with the labels that each got.

#5113 message.c: parse invalid content type as "application/octet-stream"
  cassandane/tiny-tests/JMAPEmail/email_get_bodypart_type_invalid
  cassandane/tiny-tests/SearchFuzzy/noindex_multipartheaders
  imap/message.c
Labels: include-in-fastmail

#5141 imapd.c: fix proxying UID Search (issue #5047)
  cassandane/Cassandane/Cyrus/MurderIMAP.pm
  imap/imapd.c
Labels: backport-to-3.6, backport-to-3.8, backport-to-3.10

#5144 backend: update backend_version for MAILBOX_MINOR_VERSION 19
  cunit/backend.testc
  imap/backend.c
  imap/mailbox.h
Labels: backport-to-3.10
