Repository cyrusimap/cyrus-imapd, pull requests merged in 2025-02, with the labels that each got.

#5229 cass: support newer HTTP::Tiny, Net::DAVTalk, Mail::JMAPTalk
  cassandane/Cassandane/Cyrus/TestCase.pm
  cassandane/tiny-tests/JMAPCore/echo_tls
Labels: backport-to-3.12

#5245 cass: annotate some tests with dependencies
  cassandane/Cassandane/Cyrus/FastMail.pm
  cassandane/tiny-tests/JMAPEmail/email_query_unicodefdfx
Labels: backport-to-3.12

#5247 annotate.c: only call caldav_alarm_update_floating() on calendar mailboxes
  cassandane/tiny-tests/FastMail/set_tzid_on_inbox
  imap/annotate.c
Labels: backport-to-3.12

#5225 message: make some strcmps "safe"
  imap/index.c
  imap/message.c
Labels: include-in-fastmail

#5258 Ctl conversations basecid
  imap/conversations.c
  imap/conversations.h
  imap/ctl_conversationsdb.c
Labels: include-in-fastmail

#5267 Userpath
  imap/http_caldav.c
  imap/mboxlist.c
  imap/mboxlist.h
  imap/mboxname.c
  lib/imapoptions
Labels: include-in-fastmail

#5260 mailbox: assert fail if conversations open error
  imap/mailbox.c
Labels: include-in-fastmail

#5254 Revert "message.c: reject to parse MIME headers with NUL byte"
  cassandane/tiny-tests/JMAPEmail/email_import_zerobyte
  imap/message.c
Labels: include-in-fastmail

#5157 Twom database format and first implementation
  Makefile.am
  bench/cyrdbbench.c
  changes/next/twom
  cunit/aaa-db.testc
  doc/README.twom.md
  docsrc/imap/concepts/deployment/databases.rst
  docsrc/imap/reference/manpages/systemcommands/cyr_dbtool.rst
  imap/cyr_dbtool.c
  imap/global.c
  lib/cyrusdb.c
  lib/cyrusdb.h
  lib/cyrusdb_skiplist.c
  lib/cyrusdb_twom.c
  lib/cyrusdb_twoskip.c
  lib/imapoptions
  lib/libcyr_cfg.c
  lib/libcyr_cfg.h
  lib/twom.c
  lib/twom.h
  lib/xxhash.h
Labels: include-in-fastmail

#5276 Conversations upgrade
  cassandane/Cassandane/Cyrus/Conversations.pm
  changes/next/conversations-versions
  imap/conversations.c
  imap/conversations.h
  imap/ctl_conversationsdb.c
Labels: include-in-fastmail

#5271 document mboxgroups
  cassandane/Cassandane/Cyrus/Mboxgroups.pm
  docsrc/imap/reference/admin/access-control/identifiers.rst
  imap/imapd.c
Labels: backport-to-3.12

#5291 small mboxgroups doc fixes
  docsrc/imap/concepts/overview_and_concepts.rst
  docsrc/imap/reference/admin/access-control/identifiers.rst
Labels: backport-to-3.12

#5299 master.c: Actually wait (at least) 10 seconds before attempting to restart crashing children
  cassandane/Cassandane/Cyrus/Master.pm
  master/master.c
Labels: backport-to-3.12

#5155 fix shared mailbox subscription bug when one user is prefix of other
  cassandane/Cassandane/Cyrus/Shared.pm
  cassandane/Cassandane/Cyrus/Subscriptions.pm
  cassandane/Cassandane/Instance.pm
  cassandane/Cassandane/Mboxname.pm
  cassandane/Cassandane/Test/Mboxname.pm
  cassandane/Cassandane/Util/Words.pm
  changes/next/5146-shared-subs
  imap/mboxlist.c
  lib/cyrusdb_flat.c
Labels: include-in-fastmail, backport-to-3.12
