Repository cyrusimap/cyrus-imapd, pull requests merged in 2025-03, with the labels that each got.

#5184 xunlink: clear errno and return 0 on ENOENT
  cunit/command.testc
  imap/append.c
  imap/mailbox.c
  imap/mboxkey.c
  imap/prometheus.c
  imap/seen_db.c
  imap/sievedir.c
  lib/cyrusdb_quotalegacy.c
  lib/util.c
  lib/xunlink.c
  lib/xunlink.h
Labels: include-in-fastmail

#5308 always build/install/distribute manpages
  Makefile.am
Labels: backport-to-3.12

#5330 updates to release and install docs
  CONTRIBUTING.md
  docsrc/imap/download/getcyrus.rst
  docsrc/imap/download/installation/distributions/centos.rst
  docsrc/imap/download/installation/distributions/debian.rst
  docsrc/imap/download/installation/distributions/fedora.rst
  docsrc/imap/download/installation/distributions/opensuse.rst
  docsrc/imap/download/installation/distributions/rhel.rst
  docsrc/imap/download/installation/distributions/ubuntu.rst
  docsrc/imap/download/release-notes/2.0/2.0.x.rst
  docsrc/imap/download/release-notes/2.1/2.1.x.rst
  docsrc/imap/download/release-notes/2.2/2.2.x.rst
  docsrc/imap/download/release-notes/2.3/index.rst
  docsrc/imap/download/release-notes/2.4-dav/index.rst
  docsrc/imap/download/release-notes/2.4/index.rst
  docsrc/imap/download/release-notes/2.4/x/2.4.17-caldav-beta1.rst
  docsrc/imap/download/release-notes/2.4/x/2.4.17-caldav-beta10.rst
  docsrc/imap/download/release-notes/2.4/x/2.4.17-caldav-beta11.rst
  docsrc/imap/download/release-notes/2.4/x/2.4.17-caldav-beta2.rst
  docsrc/imap/download/release-notes/2.4/x/2.4.17-caldav-beta3.rst
  docsrc/imap/download/release-notes/2.4/x/2.4.17-caldav-beta4.rst
  docsrc/imap/download/release-notes/2.4/x/2.4.17-caldav-beta5.rst
  docsrc/imap/download/release-notes/2.4/x/2.4.17-caldav-beta6.rst
  docsrc/imap/download/release-notes/2.4/x/2.4.17-caldav-beta7.rst
  docsrc/imap/download/release-notes/2.4/x/2.4.17-caldav-beta8.rst
  docsrc/imap/download/release-notes/2.4/x/2.4.17-caldav-beta9.rst
  docsrc/imap/download/release-notes/2.5/index.rst
  docsrc/imap/download/release-notes/3.0/index.rst
  docsrc/imap/download/release-notes/3.1/index.rst
  docsrc/imap/download/release-notes/3.10/index.rst
  docsrc/imap/download/release-notes/3.11/index.rst
  docsrc/imap/download/release-notes/3.12/index.rst
  docsrc/imap/download/release-notes/3.13/index.rst
  docsrc/imap/download/release-notes/3.2/index.rst
  docsrc/imap/download/release-notes/3.3/index.rst
  docsrc/imap/download/release-notes/3.4/index.rst
  docsrc/imap/download/release-notes/3.5/index.rst
  docsrc/imap/download/release-notes/3.6/index.rst
  docsrc/imap/download/release-notes/3.7/index.rst
  docsrc/imap/download/release-notes/3.8/index.rst
  docsrc/imap/download/release-notes/3.9/index.rst
  docsrc/imap/download/release-notes/index.rst
  docsrc/index.rst
Labels: documentation

#5350 docs: clean up (and strip down) developer docs
  docsrc/conf.py
  docsrc/contribute.rst
  docsrc/developers.rst
  docsrc/imap/concepts/overview_and_concepts.rst
  docsrc/imap/developer.rst
  docsrc/imap/developer/ancient-releasing.rst
  docsrc/imap/developer/compiling.rst
  docsrc/imap/developer/cyrusworks.rst
  docsrc/imap/developer/documentation.rst
  docsrc/imap/developer/github-guide.rst
  docsrc/imap/developer/jmap.rst
  docsrc/imap/developer/overview.rst
  docsrc/imap/developer/process.rst
  docsrc/imap/developer/releasing.rst
  docsrc/imap/download/getcyrus.rst
  docsrc/imap/download/installation/manage-dav.rst
  docsrc/imap/download/release-notes/3.0/x/3.0.0-beta3.rst
  docsrc/imap/download/release-notes/3.0/x/3.0.0-beta4.rst
  docsrc/imap/download/release-notes/3.0/x/3.0.0-beta5.rst
  docsrc/imap/download/release-notes/3.0/x/3.0.0-beta6.rst
  docsrc/imap/download/release-notes/3.0/x/3.0.0-rc1.rst
  docsrc/imap/download/release-notes/3.0/x/3.0.0-rc2.rst
  docsrc/imap/download/release-notes/3.0/x/3.0.0-rc3.rst
  docsrc/imap/download/release-notes/3.0/x/3.0.0-rc4.rst
  docsrc/imap/download/release-notes/3.0/x/3.0.0.rst
  docsrc/imap/quickstart/introduction.rst
  docsrc/imap/reference/faq.rst
  docsrc/imap/support/feedback-mailing-lists.rst
  docsrc/index.rst
  docsrc/overview/cyrus_roadmap.rst
Labels: documentation

#5319 Fix for deadlock on shutdown
  master/master.c
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8, backport-to-3.10, backport-to-3.12

#5356 Buf mmap fix length
  lib/map_nommap.c
  lib/map_shared.c
  lib/map_stupidshared.c
Labels: include-in-fastmail
