Repository cyrusimap/cyrus-imapd, pull requests merged in 2025-01, with the labels that each got.

#5185 Created mailbox check
  cassandane/tiny-tests/JMAPMailbox/mailbox_changes_create_delete
  imap/jmap_mailbox.c
Labels: include-in-fastmail

#5173 Clearmodseq
  cassandane/Cassandane/Cyrus/Conversations.pm
  changes/next/clearmodseq
  docsrc/imap/reference/manpages/systemcommands/ctl_conversationsdb.rst
  imap/conversations.c
  imap/conversations.h
  imap/ctl_conversationsdb.c
  imap/global.c
  imap/global.h
  imap/mailbox.c
  imap/mboxname.c
  imap/mboxname.h
Labels: include-in-fastmail

#5193 twoskip: free transaction after repack
  lib/cyrusdb_twoskip.c
Labels: include-in-fastmail

#5198 configure.ac: want sphinx_rtd_theme for doc builds
  changes/next/docs-sphinx-rtd-theme
  configure.ac
  docsrc/imap/developer/compiling.rst
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8, backport-to-3.10, backport-to-3.12

#5205 message.c: reject to parse MIME headers with NUL byte
  cassandane/tiny-tests/JMAPEmail/email_import_zerobyte
  imap/message.c
Labels: include-in-fastmail

#5061 alpaca mitigations
  cassandane/Cassandane/Cyrus/Alpaca.pm
  cunit/imparse.testc
  imap/httpd.c
  imap/imapd.c
  lib/imparse.c
  lib/imparse.h
Labels: include-in-fastmail, backport-to-3.12

#5176 SieveScript/test: Allow prepopulating variables so your sieve scripts can behave differently during test
  cassandane/Cassandane/Cyrus/JMAPSieve.pm
  cassandane/tiny-tests/JMAPSieve/sieve-test-extensive
  cassandane/tiny-tests/JMAPSieve/sieve-test-variables
  cassandane/tiny-tests/JMAPSieve/sieve-test-variables-validation
  cunit/sieve.testc
  imap/jmap_sieve.c
  imap/lmtp_sieve.c
  sieve/bc_eval.c
  sieve/grammar.c
  sieve/grammar.h
  sieve/message.c
  sieve/script.c
  sieve/sieve.y
  sieve/sieve_interface.h
  sieve/test.c
  sieve/test_mailbox.c
Labels: include-in-fastmail

#5221 Minifixes
  imap/global.c
  imap/mailbox.c
  lib/bsearch.c
  lib/bsearch.h
  lib/cyrusdb.c
  lib/cyrusdb.h
  lib/cyrusdb_skiplist.c
  master/service.c
Labels: backport-to-3.12

#5162 Sieve: allow private Final-Recipient in rejects, allow non-Original-Recipient header for original recipient.
  changes/next/sieve_mdn_original_recipient_header
  changes/next/sieve_mdn_private
  imap/lmtp_sieve.c
  lib/imapoptions
Labels: include-in-fastmail

#5166 Don't send the "action strings" when notifying
  changes/next/notify_action_string
  sieve/script.c
Labels: include-in-fastmail

#5219 apply implicit owner rights in JMAP API
  cassandane/tiny-tests/JMAPMailbox/mailbox_set
  changes/next/http_implicit_acls
  imap/httpd.c
Labels: include-in-fastmail

#5233 SieveScript/test: Support duplicate and environment extensions
  cassandane/tiny-tests/JMAPSieve/sieve-test-extensive
  imap/jmap_sieve.c
Labels: include-in-fastmail

#5237 sync_support: don't blat 'r' for SIEVE mailboxes
  imap/sync_support.c
Labels: include-in-fastmail

#5242 Add Caldav.calendar_query_dtend_tzid
  cassandane/tiny-tests/Caldav/calendar_query_dtend_tzid
Labels: include-in-fastmail
