Repository cyrusimap/cyrus-imapd, pull requests merged in 2025-05, with the labels that each got.

#5402 fatal sphinx-build warnings when release checks enabled
  Makefile.am
Labels: backport-to-3.6, backport-to-3.4, backport-to-3.2, backport-to-3.8, backport-to-3.10, backport-to-3.12

#5386 Fsync mkdir
  imap/append.c
  imap/mailbox.c
  imap/mailbox.h
  imap/sync_support.c
  imap/unexpunge.c
  lib/mappedfile.c
  lib/twom.c
  lib/util.c
  lib/util.h
Labels: include-in-fastmail

#5407 jmap_calendars.c: add support for fetching mailbox uniqueid
  cassandane/tiny-tests/JMAPCalendars/calendar_set
  imap/jmap_calendar.c
Labels: include-in-fastmail

#5426 charset: needs stdbool.h for bool type
  lib/charset.c
Labels: backport-to-3.12

#5425 cyr_info: recognise service-prefixed sasl keys in conf-lint
  cassandane/Cassandane/Cyrus/Info.pm
  imap/cyr_info.c
Labels: backport-to-3.8, backport-to-3.10, backport-to-3.12

#5120 imapd.c: Implement IMAP UIDBATCHES
  cassandane/Cassandane/Cyrus/UIDbatches.pm
  changes/next/imap-uidbatches
  docsrc/imap/rfc-support.rst
  imap/imapd.c
  imap/imapd.h
  imap/promdata.p
  lib/imapoptions
Labels: include-in-fastmail

#5437 tls.c: don't leak SSL_SESSIONs when caching
  cassandane/Cassandane/Cyrus/ALPN.pm
  cassandane/Cassandane/Cyrus/Alpaca.pm
  cassandane/Cassandane/Cyrus/MboxEvent.pm
  cassandane/Cassandane/Cyrus/StartTLS.pm
  cassandane/tiny-tests/JMAPCore/echo_tls
  imap/tls.c
Labels: Do Not Merge, include-in-fastmail

#5453 http_admin: fix double-free in action_proc()
  imap/http_admin.c
Labels: backport-to-3.6, backport-to-3.8, backport-to-3.10, backport-to-3.12
